---

- hosts: localhost
  roles:
    - base
    - utils
    - git
    - php
    - node
    - intelij
    - docker
  tasks:
    - name: "display post install message"
      debug:
        msg:
          - 'things left to do:'
          - 'Reboot your sistem!'
