---

- hosts: localhost
  roles:
    - base
    - utils
    - git
    - php
    - node
    - intelij
    - docker
    - openjdk
  tasks:
    - name: "Post post install recommendations message"
      debug:
        msg:
          - 'things left to do:'
          - 'rclone config'
          # - 'dropbox start -i'
          - 'Reboot your sistem'
          - 'Enjoy!'
