---

- name: Epiphany Web Browser
  apt:
    name: epiphany-browser
    state: "{{ 'present' if epiphany else 'absent' }}"

- name: Firefox Web Browser
  apt:
    name: firefox
    state: "{{ 'present' if firefox else 'absent' }}"

- name: Gnome Disk Utility
  apt:
    name: gnome-disk-utility
    state: "{{ 'present' if gnome_disk_utility else 'absent' }}"

- name: Install snapd
  apt:
    name: snapd
    state: "{{ 'present' if snapd else 'absent' }}"

- import_tasks: pmv-player.yml

- name: pantheon-mail
  apt:
    name: pantheon-mail
    state: "{{ 'present' if pantheon_mail else 'absent' }}"

- name: Mailspring
  snap:
    name: mailspring
    state: "{{ 'present' if snapd and mailspring else 'absent' }}"
  become: true
  become_user: root

- import_tasks: rclone.yml
