---
- name: Check if rclone is installed
  package_facts:
    manager: "auto"

- block:
    - name: Check latest rclone stable version
      uri:
        url: https://downloads.rclone.org/version.txt
        return_content: true
      register: rclone_latest_version
      check_mode: false
    - name: Set rclone_version variable to latest stable version number
      set_fact:
        rclone_version: "{{ rclone_latest_version.content | replace ('rclone v', '', 1) | trim }}"
  when: "rclone_version is undefined and 'rclone' not in ansible_facts.packages and rclone"

- name: Uninstall rclone
  apt:
    name: rclone
    state: absent
  when: "not rclone"

- name: Install rclone stable version {{ rclone_version }}
  apt:
    deb: https://downloads.rclone.org/v{{ rclone_version }}/rclone-v{{ rclone_version }}-linux-amd64.deb
    state: present
  when: "rclone and 'rclone' not in ansible_facts.packages"
