---

- name: install git
  apt:
    name: git
    state: "{{ 'present' if git else 'absent' }}"

- name: install dependencies
  apt:
    name:
      - libgnome-keyring-common
      - libgnome-keyring-dev
    state: "{{ 'present' if git else 'absent' }}"

# install git craken
- name: GitKraken
  snap:
    name: gitkraken
    state: "{{ 'present' if snapd and gitkraken else 'absent' }}"
  become: true
  become_user: root

