---

- name: install git
  apt:
    name: git
    state: present

- name: install dependencies
  apt: name="{{item}}"
  with_items:
    - libgnome-keyring-common
    - libgnome-keyring-dev

# install git craken
- name: download and install git cracken
  apt:
    deb: https://release.gitkraken.com/linux/gitkraken-amd64.deb

