---


# need to add cron jobs to purne docker system and free up storage

- block:
  - name: add docker signing key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
    when: docker

  - name: add docker repository
    apt_repository:
      state: "{{ 'present' if docker else 'absent' }}"
      repo: >
        deb [arch=amd64]
        https://download.docker.com/linux/ubuntu
        bionic stable

  - name: Install Docker
    apt:
      name:
        - "docker-{{docker_edition}}"
        - "docker-{{docker_edition}}-cli"
        - "containerd.io"
      state: "{{ 'present' if docker else 'absent' }}"

- name: create docker configuration directories
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: docker
  loop:
    - /etc/docker
    - /etc/systemd/system/docker.service.d

- name: configure docker daemon options (json)
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  when: docker

- name: add local user to docker group
  user:
    name: "{{local_user}}"
    groups: docker
    append: true
  when: docker

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: "{{ 'present' if docker else 'absent' }}"
    extra_args: --user
  become: "{{local_user}}"

