---

- name: install php
  apt:
    name: php
    state: present

- name: insall extensions
  apt:
    name: "{{item}}"
  loop: "{{php_extensions}}"

- name: install composer
  get_url:
    url: "https://getcomposer.org/download/{{composer_version}}/composer.phar"
    dest: /usr/bin/composer
    mode: o=rx

- name: install phpunit
  get_url:
    url: "https://phar.phpunit.de/phpunit-{{phpunit_version}}.phar"
    dest: /usr/bin/phpunit
    mode: o=rx

- name: make sure apache is not present
  apt:
    name: apache2
    state: absent
